# Default value.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
appName: apiRestDev

image:
  pullPolicy: IfNotPresent
  tag: latest
  repository: marcoscianci/shipay-api-rest

resources:
  limits:
    cpu: 200m
    memory: 250Mi
  requests:
    cpu: 200m
    memory: 250Mi

service:
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000

ingress:
  enabled: true
  domain: "apirest-dev.shipay.test.org"

# metrics-server add-on required
hpa:
  enabled: true
  maxReplicas: 2
  # average total CPU usage per pod (1-100)
  cpu: 70
  # average memory usage per pod (100Mi-1Gi)
  memory:
  # average http requests per second per pod (k8s-prometheus-adapter)
  requests:

environments:
