name: Deploy Shipay ApiRest

on: push


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          Username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true 
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.PROJECT }}:latest
              
      - name: Image Digest 
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: self-hosted
    needs: build 

    steps:
      
      - name: Get minikube status
        run: minikube status

      - name: Get cluster info
        run: kubectl cluster-info

      - name: Get Kubernetes Pods 
        run: kubectl get pods --all-namespaces

      - name: Get Minikube IP
        run: minikube ip
      
     